[package]
name = "exclave"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]

[dependencies]
console = "0.5.0"
notify = "4.0.1"
clap = "2.26.0"
ctrlc = "3.0.2"
systemd-parser = "0.1.3"
runny = "1.0.1"
regex = "0.2.2"